# nvfetcher.toml
[clipcat]
src.git = "https://github.com/wrvsrx/clipcat"
fetch.github = "wrvsrx/clipcat"
cargo_locks = [ "Cargo.lock" ]

[osc52]
src.github_tag = "wrvsrx/osc52"
fetch.github = "wrvsrx/osc52"

[giraffe-wallpaper]
src.git = "https://github.com/wrvsrx/giraffe-wallpaper"
fetch.github = "wrvsrx/giraffe-wallpaper"

[autodiff]
src.github_tag = "autodiff/autodiff"
fetch.github = "autodiff/autodiff"

[taskwarrior-to-dot]
src.git = "https://github.com/wrvsrx/taskwarrior-to-dot"
fetch.github = "wrvsrx/taskwarrior-to-dot"
