# nvfetcher.toml
[osc52]
src.git = "https://github.com/wrvsrx/osc52"
fetch.github = "wrvsrx/osc52"

[giraffe-wallpaper]
src.git = "https://github.com/wrvsrx/giraffe-wallpaper"
fetch.github = "wrvsrx/giraffe-wallpaper"

[autodiff]
src.github_tag = "autodiff/autodiff"
fetch.github = "autodiff/autodiff"

[taskwarrior-utils]
src.git = "https://github.com/wrvsrx/taskwarrior-to-dot"
fetch.github = "wrvsrx/taskwarrior-to-dot"

[noto-fonts-emoji-monochrome]
src.git = "https://github.com/wrvsrx/noto-emoji"
fetch.github = "wrvsrx/noto-emoji"

[xclip]
src.git = "https://github.com/astrand/xclip"
fetch.github = "astrand/xclip"

[autobean-format]
src.git = "https://github.com/SEIAROTg/autobean-format"
fetch.github = "SEIAROTg/autobean-format"

[autobean-refactor]
src.git = "https://github.com/SEIAROTg/autobean-refactor"
fetch.github = "SEIAROTg/autobean-refactor"

[vdirsyncer]
src.git = "https://github.com/wrvsrx/vdirsyncer"
src.branch = "use-vcard-4"
fetch.github = "wrvsrx/vdirsyncer"

[nvim-numbertoggle]
src.git = "https://github.com/sitiom/nvim-numbertoggle"
fetch.github = "sitiom/nvim-numbertoggle"

[coc-zk]
src.git = "https://github.com/wrvsrx/coc-zk"
fetch.github = "wrvsrx/coc-zk"

[compdb]
src.pypi = "compdb"
fetch.pypi = "compdb"

[OpenEXR]
src.pypi = "OpenEXR"
fetch.pypi = "OpenEXR"

[googletrans]
src.manual = "4.0.0rc1"
fetch.pypi = "googletrans"

[cyCodeBase]
src.git = "https://github.com/cemyuksel/cyCodeBase"
fetch.github = "cemyuksel/cyCodeBase"

[lyra]
src.git = "https://github.com/bfgroup/Lyra"
fetch.github = "bfgroup/Lyra"

[hougeo]
src.git = "https://github.com/nyue/hougeo"
fetch.github = "nyue/hougeo"

[happly]
src.git = "https://github.com/nmwsharp/happly"
fetch.github = "nmwsharp/happly"

[cnpy]
src.git = "https://github.com/rogersce/cnpy"
fetch.github = "rogersce/cnpy"

[amgcl]
src.github_tag = "ddemidov/amgcl"
fetch.github = "ddemidov/amgcl"

[yalantinglibs]
src.github_tag = "alibaba/yalantinglibs"
fetch.github = "alibaba/yalantinglibs"

[calendar-visualization]
src.git = "https://github.com/wrvsrx/calendar-visualization"
fetch.github = "wrvsrx/calendar-visualization"

[structopt]
src.github_tag = "p-ranav/structopt"
fetch.github = "p-ranav/structopt"

[utfcpp]
src.github_tag = "nemtrif/utfcpp"
fetch.github = "nemtrif/utfcpp"

[seal_lake]
src.git = "https://github.com/kamchatka-volcano/seal_lake"
fetch.github = "kamchatka-volcano/seal_lake"

[sfun]
src.github_tag = "kamchatka-volcano/sfun"
fetch.github = "kamchatka-volcano/sfun"

[cmdlime]
src.git = "https://github.com/kamchatka-volcano/cmdlime"
fetch.github = "kamchatka-volcano/cmdlime"

[spdlog]
src.git = "https://github.com/gabime/spdlog"
fetch.github = "gabime/spdlog"

[rsshub]
src.git = "https://github.com/DIYGod/RSSHub"
fetch.github = "DIYGod/RSSHub"

[metacubexd]
src.github_tag = "MetaCubeX/metacubexd"
fetch.github = "MetaCubeX/metacubexd"

[auth-thu]
src.git = "https://github.com/z4yx/GoAuthing"
fetch.github = "z4yx/GoAuthing"

[compat-list]
src.git = "https://github.com/flathub/org.yuzu_emu.yuzu"
fetch.github = "flathub/org.yuzu_emu.yuzu"

[nx_tzdb]
src.github_tag = "lat9nq/tzdb_to_nx"
fetch.url = "https://github.com/lat9nq/tzdb_to_nx/releases/download/$ver/$ver.zip"

[linediff-vim]
src.git = "https://github.com/AndrewRadev/linediff.vim"
fetch.git = "https://github.com/AndrewRadev/linediff.vim"

[iCalendar]
src.git = "https://github.com/wrvsrx/iCalendar"
fetch.github = "wrvsrx/iCalendar"

[noto-fonts-cjk-sans-fix-weight]
src.manual = "Sans2.004"
fetch.github = "notofonts/noto-cjk"
git.sparseCheckout = [ "Sans/OTC" ]

[noto-fonts-cjk-serif-fix-weight]
src.manual = "Serif2.002"
fetch.github = "notofonts/noto-cjk"
git.sparseCheckout = [ "Serif/OTC" ]

[baikal]
# src.github_tag = "sabre-io/Baikal"
src.manual = "0.9.5"
fetch.github = "sabre-io/Baikal"
