# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  clipcat = {
    pname = "clipcat";
    version = "13b7c4e4065721c4ea6839a8b9d33d0324a65b1b";
    src = fetchFromGitHub ({
      owner = "wrvsrx";
      repo = "clipcat";
      rev = "13b7c4e4065721c4ea6839a8b9d33d0324a65b1b";
      fetchSubmodules = false;
      sha256 = "sha256-55FQPX0/6A5Dm6yZ8FqxN4PM6EOPnG3FYti7B/k4XlE=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./clipcat-13b7c4e4065721c4ea6839a8b9d33d0324a65b1b/Cargo.lock;
      outputHashes = {
        "x11-clipboard-0.7.0" = "sha256-ToDy7vWPRYk8mrmL+77HJypE91b6z/NaDTUDgRe20d0=";
      };
    };
    date = "2023-01-14";
  };
}
