# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  clipcat = {
    pname = "clipcat";
    version = "13b7c4e4065721c4ea6839a8b9d33d0324a65b1b";
    src = fetchFromGitHub ({
      owner = "wrvsrx";
      repo = "clipcat";
      rev = "13b7c4e4065721c4ea6839a8b9d33d0324a65b1b";
      fetchSubmodules = false;
      sha256 = "sha256-55FQPX0/6A5Dm6yZ8FqxN4PM6EOPnG3FYti7B/k4XlE=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./clipcat-13b7c4e4065721c4ea6839a8b9d33d0324a65b1b/Cargo.lock;
      outputHashes = {
        "x11-clipboard-0.7.0" = "sha256-ToDy7vWPRYk8mrmL+77HJypE91b6z/NaDTUDgRe20d0=";
      };
    };
    date = "2023-01-14";
  };
  giraffe-wallpaper = {
    pname = "giraffe-wallpaper";
    version = "2240da13220a6c04a9d39a42c4da40f8b3327be8";
    src = fetchFromGitHub ({
      owner = "wrvsrx";
      repo = "giraffe-wallpaper";
      rev = "2240da13220a6c04a9d39a42c4da40f8b3327be8";
      fetchSubmodules = false;
      sha256 = "sha256-ChGql5Or/J150c1lg2Pg6Cc/ZH0k69zMW1G2QTvy1wk=";
    });
    date = "2023-01-07";
  };
  osc52 = {
    pname = "osc52";
    version = "0.1.0.0";
    src = fetchFromGitHub ({
      owner = "wrvsrx";
      repo = "osc52";
      rev = "0.1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-JAhA7bdzcRWokvHjMt5Hk6uwOkNFxalQ2xe0Z4bzRp4=";
    });
  };
}
