name: "Build and populate cache"
on:
  pull_request:
  push:
  schedule:
    # rebuild everyday at 2:51
    # TIP: Choose a random time here so not all repositories are build at once:
    # https://www.random.org/clock-times/?num=1&earliest=01%3A00&latest=08%3A00&interval=5&format=html&rnd=new
    - cron:  '51 2 * * *'
jobs:
  tests:
    strategy:
      matrix:
        # Set this to notify the global nur package registry that changes are
        # available.
        #
        # The repo name as used in
        # https://github.com/nix-community/NUR/blob/master/repos.json
        nurRepo:
          - wrvsrx
        # Set this to cache your build results in cachix for faster builds
        # in CI and for everyone who uses your cache.
        #
        # Format: Your cachix cache host name without the ".cachix.org" suffix.
        # Example: mycache (for mycache.cachix.org)
        #
        # For this to work, you also need to set the CACHIX_SIGNING_KEY or
        # CACHIX_AUTH_TOKEN secret in your repository secrets settings in
        # Github found at
        # https://github.com/<your_githubname>/nur-packages/settings/secrets
        # cachixName:
        #   - <YOUR_CACHIX_NAME>
        # nixPath:
        #   - nixpkgs=channel:nixos-unstable
        #   - nixpkgs=channel:nixpkgs-unstable
        #   - nixpkgs=channel:nixos-22.11
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v25
      with:
        # nix_path: "${{ matrix.nixPath }}"
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Show flake metadata
      run: nix flake metadata
    - name: Show flake information
      run: nix flake show
    - name: Check evaluation
      run: nix flake check --no-build
    - name: Build nix packages
      run: nix flake check -v
